services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  redis:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-storage:/data

volumes:
  grafana-storage:
  redis-storage:
